services:
  db:
    container_name: "agromartDB"
    image: postgres:18-alpine3.23
    volumes:
      - "./database/postgres-data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped

  app:
    container_name: "agromartApp"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
    restart: unless-stopped